### ISSUE TITLE
bnl_dis.pl not functioning (WIN7, strawberry-perl-5.32.1.1-64bit)

### ISSUE THREAD

**Issue by Tojda** [jindroush/albituzka#1]
C:\Strawberry_Perl>bnl_dis.pl Pexeso_Dopravni_prostredky.bnl -extract
Bareword found where operator expected at C:\Strawberry_Perl\bnl_dis.pl line 8,
near ""en" data"
        (Missing operator before data?)
Bareword found where operator expected at C:\Strawberry_Perl\bnl_dis.pl line 8,
near ""auto" data"
        (Missing operator before data?)
Bareword found where operator expected at C:\Strawberry_Perl\bnl_dis.pl line 8,
near ""light" data"
        (Missing operator before data?)
Can't modify numeric lt (<) in scalar assignment at C:\Strawberry_Perl\bnl_dis.p
l line 8, near ""en" data"
syntax error at C:\Strawberry_Perl\bnl_dis.pl line 8, near ""en" data"
Excessively long <> operator at C:\Strawberry_Perl\bnl_dis.pl line 20.

**Comment by jindroush** [comment]
Looks to me like incorrect file. How did you download it?
this is raw file, it should look the same: 
https://raw.githubusercontent.com/jindroush/albituzka/main/tools/disassembler/bnl_dis.pl

**Comment by Tojda** [comment]
My fault, sorry! I downloaded the file via "Save link as"... But I managed to download the file correctly somehow (2 days ago and I do not remeber how :-)). GitHub is new to me and I really do not know hot to download the files easy and correct way :-/. Now I am struggling with MP3 and YAML installation - some errors occure and I try to figure it out :-/...

**Comment by jindroush** [comment]
in strawberry YAML should be pre-installed and MP3::Info installation is mentioned in the last article at tatageeks'
Starting with perl -c bnl_dis.pl should give you the exact names of modules to install

**Comment by Tojda** [comment]
I guess that it was not a good idea to choose other folder name (Strawbery_Perl) for strawberry installation... Because while trying to install MP3::Info modul, files were installed into Strawberry folder. I unistalled Strawberry and installed it again (to Strawberry folder), isntalled MP3:Info modul and everything seem to be working now. Thank you for your effort to help! Appreciate it!

**Comment by jindroush** [comment]
Hm, I installed Strawberry to c:\perl on the test machine and it worked - what you describe looks like misconfiguration of CPAN module.
Nevermind, it's working so I'm closing the issue.

**Comment by jindroush** [comment]
Is the. Pl file raw file? Ie does it start with # (Not currently at
computer, but this looks like most probable cause)

**Comment by Edss714** [comment]
Ojj
