### ISSUE TITLE
dotaz

### ISSUE THREAD

**Issue by marthyg76** [jindroush/albituzka#3]
Dobrý den,
je na Vás možný nějaký mobil nebo e-mail? Nebo mi můžete napsat na maazaa76@gmail.com. Nebo mobil 608 334 639.
Mám pro Vás nějaký projekt, možná by Vás mohl zajímat:)

děkuji 
S pozdravem
Gärtner

**Comment by jindroush** [comment]
Zodpovezeno privatne.

**Comment by jindroush** [comment]
Zodpovezeno privatne.
